Feedback form
AkhilSamarth/cs490-poligram pull request #13
Opened 2020-11-11 19:09 UTC by Hammad-Akbar

Created tables for feedback form, react components associated with it and edited the readme.

2020-11-12 16:15 UTC, aminJayP approved these changes

2020-11-12 16:17 UTC, svp62 approved these changes

2020-11-12 16:42 UTC, AkhilSamarth requested changes

2020-11-12 16:42 UTC, AkhilSamarth commented on app.py
> +db.session.commit()
I would leave this in models.py. I found a post online which said that leaving this part in models helps solve some of those weird circular reference issues (I guess because it ensures that the tables are created within models.py rather than in app).

2020-11-12 16:42 UTC, AkhilSamarth commented on models.py
> +    id = db.Column(db.Integer, primary_key=True)
Apparently the spec says that we have to use email as the primary key.

2020-11-12 16:42 UTC, AkhilSamarth commented on models.py
> +class FeedbackLog(db.Model):
Might be a good idea to add an explicit \_\_tablename__, but up to you on that one.

2020-11-12 16:42 UTC, AkhilSamarth commented on scripts/Components/FeedbackButton.jsx
> +  const newName = document.getElementById('name_input');
I think Sresht mentioned at some point that we should avoid getElementById since it's not "the React way", so to speak (React uses refs), but I think for MVP this is fine. Maybe change for sprint 2 though.

2020-11-12 16:42 UTC, AkhilSamarth commented on scripts/Components/Home.jsx
> +            });
Make sure you add a cleanup function at the end of useEffect to disable the "feedback sent" listener. Otherwise, we may end up with duplicate listeners.

2020-11-12 16:42 UTC, AkhilSamarth commented on models.py
> +class FeedbackLog(db.Model):
Yeah, found it. Under user login:

"OAuth required, and the user must be uniquely identified in your database/app usingtheir email (not name or any other identifier)"

Sorry, would've told you before but I didn't realize we had to use email.

2020-11-12 16:43 UTC, Hammad-Akbar commented on models.py
> +    id = db.Column(db.Integer, primary_key=True)
is that an mvp requirement? we can change that in sprint two when we incorporate oauth further.

2020-11-13 00:48 UTC, AkhilSamarth approved these changes

2020-11-13 00:50 UTC, merged