Merge: Google login
AkhilSamarth/cs490-poligram pull request #7
Opened 2020-11-08 17:59 UTC by aminJayP

Completed google login

2020-11-08 22:07 UTC, AkhilSamarth requested changes

2020-11-08 22:07 UTC, AkhilSamarth commented on app.py
> +    socketio.emit('new connection', {
sorry, I haven't used rooms before. what does "new connection" event do and what's the room for?

2020-11-08 22:07 UTC, AkhilSamarth commented on scripts/Components/LoginPage.jsx
> +    alert(error);
I think it might be better to show a user-friendly alert (e.g. "Sorry, login failed") rather than directly showing the error.

2020-11-08 22:07 UTC, AkhilSamarth commented on scripts/Content.jsx
> +    Socket.on('new connection', (data) => {
needs a cleanup function to disable the listener to avoid duplicate listeners.

2020-11-08 22:07 UTC, AkhilSamarth commented on scripts/Content.jsx
> +      window.removeEventListener('beforeunload', () => {
what does this do?

2020-11-08 22:15 UTC, aminJayP commented on app.py
> +    socketio.emit('new connection', {
It splits the socket id, by room. So, like if I remove room from the code, and you website opened on one tab, and after logging in the landing page will show Welcome Akhil, and then I decide to login it will change the useState for username for everyone. So, now you and I both see Welcome Jay. That is the reason for using room, and that's how I did it for the Chat App.

2020-11-08 22:17 UTC, aminJayP commented on scripts/Content.jsx
> +      window.removeEventListener('beforeunload', () => {
It is equivalent to component did unmount. So after the components is closed it will act as a cleanup function

2020-11-08 22:52 UTC, AkhilSamarth commented on scripts/Content.jsx
> +      window.removeEventListener('beforeunload', () => {
sorry, I meant the "beforeunload" event. I didn't see the listener for that anywhere, so I was wondering what this did.

2020-11-09 14:35 UTC, AkhilSamarth requested changes

2020-11-09 14:35 UTC, AkhilSamarth commented on scripts/Content.jsx
> +        Socket.close();
Is this the cleanup for the "new connection"? If so, I don't think we should be closing the socket completely. You can just disable the listener by using "Socket.off("new connection")" and remove the window.removeEventListener stuff.

2020-11-09 14:56 UTC, AkhilSamarth approved these changes

2020-11-09 16:04 UTC, merged